---
include:
  - board: ergohaven
    shield: velvet_v3_ui_left
  - board: ergohaven
    shield: velvet_v3_ui_qube qube dongle_screen
    keymap: velvet_v3_ui_ruen
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_DONGLE_SCREEN_MAX_BRIGHTNESS=30
    artifact-name: velvet_v3_ui_qube_ruen-ergohaven-zmk
  - board: ergohaven
    shield: velvet_v3_ui_right_qube

  - board: ergohaven
    shield: settings_reset
